# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.3.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-02-05T12:01:59Z"
  labels:
    app: linregapp-pod
  name: linregapp-pod
spec:
  containers:
  - image: localhost/linreg-app:latest
    name: linregapp

