# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.3.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-02-07T08:36:18Z"
  labels:
    app: preprocess-service-pod
  name: preprocess-service-pod
spec:
  containers:
  - image: docker.io/mlevytskyi089/linreg-app:latest
    name: preprocess-service
    ports:
    - containerPort: 5001
      hostPort: 5001

