# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.3.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-02-07T08:34:23Z"
  labels:
    app: linreg-service-pod
  name: linreg-service-pod
spec:
  containers:
  - image: docker.io/mlevytskyi089/linreg-app:latest
    name: linreg-service
    ports:
    - containerPort: 5000
      hostPort: 5000

